PART A

In [1]:
import numpy as np
import pandas as pd

def haversine(lat1, lon1, lat2, lon2):
    R = 6371 # radius of Earth in kilometers
    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)
    a = np.sin(delta_phi/2)**2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda/2)**2
    res = R * (2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a)))
    return np.round(res, 2)

def nearest_neighbor(depot, customers):
    remaining_customers = set(customers)
    current_location = depot
    delivery_route = [depot]

    while remaining_customers:
        min_distance = float('inf')
        nearest_customer = None
        for customer in remaining_customers:
            distance = haversine(current_location[0], current_location[1], customer[0], customer[1])
            if distance < min_distance:
                min_distance = distance
                nearest_customer = customer
        delivery_route.append(nearest_customer)
        remaining_customers.remove(nearest_customer)
        current_location = nearest_customer

    delivery_route.append(depot)  # Return to depot
    return delivery_route

def calculate_route_distance(route):
    distance = 0
    for i in range(len(route) - 1):
        distance += haversine(route[i][0], route[i][1], route[i+1][0], route[i+1][1])
    return distance

def find_best_delivery_route(input_file, output_file):
    df = pd.read_csv(input_file)
    depot_lat = df['depot_lat'].iloc[0]
    depot_lng = df['depot_lng'].iloc[0]
    depot = (depot_lat, depot_lng)
    customers = list(zip(df['lat'], df['lng']))

    best_route = nearest_neighbor(depot, customers)
    best_distance = calculate_route_distance(best_route)

    df['dlvr_seq_num'] = range(1, len(df) + 1)
    df.to_csv(output_file, index=False)

    with open('part_a_best_routes_distance_travelled.csv', 'a') as f:
        f.write(f"{input_file},{best_distance} kms\n")

    with open('part_a_details.txt', 'a') as f:
        f.write("Algorithm: Nearest Neighbor Algorithm\n")
        f.write("Time Complexity: O(n^2)\n")
        f.write("Space Complexity: O(n)\n")

# Example usage:
input_files = ['part_a_input_dataset_1.csv', 'part_a_input_dataset_2.csv', 'part_a_input_dataset_3.csv',
               'part_a_input_dataset_4.csv', 'part_a_input_dataset_5.csv']
output_files = ['part_a_output_dataset_1.csv', 'part_a_output_dataset_2.csv', 'part_a_output_dataset_3.csv',
                'part_a_output_dataset_4.csv', 'part_a_output_dataset_5.csv']

for i in range(len(input_files)):
    find_best_delivery_route(input_files[i], output_files[i])

In [11]:
pd.read_csv("part_a_output_dataset_5.csv")

    order_id        lng       lat  depot_lat  depot_lng  dlvr_seq_num
0    2349221  126.55716  43.81811    43.8121   126.5669             1
1    1720666  126.54845  43.82043    43.8121   126.5669             2
2     935442  126.56893  43.81414    43.8121   126.5669             3
3    2119726  126.57000  43.81954    43.8121   126.5669             4
4    1898768  126.56574  43.82126    43.8121   126.5669             5
5    2977295  126.53659  43.80667    43.8121   126.5669             6
6      98750  126.55001  43.82377    43.8121   126.5669             7
7    1967889  126.56403  43.82447    43.8121   126.5669             8
8     512980  126.57915  43.82581    43.8121   126.5669             9
9    1163945  126.56808  43.82254    43.8121   126.5669            10
10   4312189  126.55094  43.81513    43.8121   126.5669            11
11   2918628  126.57607  43.82599    43.8121   126.5669            12
12   2752609  126.55480  43.80953    43.8121   126.5669            13
13    689448  126.55272  43.82785    43.8121   126.5669            14
14    619869  126.59201  43.77702    43.8121   126.5669            15
15    323232  126.56633  43.80800    43.8121   126.5669            16
16   3143754  126.55921  43.81791    43.8121   126.5669            17
17   2686188  126.56021  43.80409    43.8121   126.5669            18
18     66954  126.59199  43.82113    43.8121   126.5669            19
19   1331947  126.54723  43.82336    43.8121   126.5669            20
20   2561510  126.49273  43.76271    43.8121   126.5669            21
21   3639929  126.55293  43.79402    43.8121   126.5669            22
22    884300  126.54414  43.82441    43.8121   126.5669            23
23   1972934  126.56047  43.80009    43.8121   126.5669            24
24   3024356  126.54393  43.82416    43.8121   126.5669            25

In [12]:
pd.read_csv("part_a_input_dataset_5.csv")

    order_id        lng       lat  depot_lat  depot_lng
0    2349221  126.55716  43.81811    43.8121   126.5669
1    1720666  126.54845  43.82043    43.8121   126.5669
2     935442  126.56893  43.81414    43.8121   126.5669
3    2119726  126.57000  43.81954    43.8121   126.5669
4    1898768  126.56574  43.82126    43.8121   126.5669
5    2977295  126.53659  43.80667    43.8121   126.5669
6      98750  126.55001  43.82377    43.8121   126.5669
7    1967889  126.56403  43.82447    43.8121   126.5669
8     512980  126.57915  43.82581    43.8121   126.5669
9    1163945  126.56808  43.82254    43.8121   126.5669
10   4312189  126.55094  43.81513    43.8121   126.5669
11   2918628  126.57607  43.82599    43.8121   126.5669
12   2752609  126.55480  43.80953    43.8121   126.5669
13    689448  126.55272  43.82785    43.8121   126.5669
14    619869  126.59201  43.77702    43.8121   126.5669
15    323232  126.56633  43.80800    43.8121   126.5669
16   3143754  126.55921  43.81791    43.8121   126.5669
17   2686188  126.56021  43.80409    43.8121   126.5669
18     66954  126.59199  43.82113    43.8121   126.5669
19   1331947  126.54723  43.82336    43.8121   126.5669
20   2561510  126.49273  43.76271    43.8121   126.5669
21   3639929  126.55293  43.79402    43.8121   126.5669
22    884300  126.54414  43.82441    43.8121   126.5669
23   1972934  126.56047  43.80009    43.8121   126.5669
24   3024356  126.54393  43.82416    43.8121   126.5669

In [14]:
pd.read_csv("part_a_best_routes_distance_travelled.csv")

   part_a_input_dataset_1.csv   4.54 kms
0  part_a_input_dataset_2.csv  11.93 kms
1  part_a_input_dataset_3.csv  21.11 kms
2  part_a_input_dataset_4.csv   23.8 kms
3  part_a_input_dataset_5.csv  38.82 kms

PART B

------------------------------------------------------------------------

In [ ]:
import pandas as pd
import itertools

# Read input datasets
input_data_1 = pd.read_csv("part_b_input_dataset_1.csv")
input_data_2 = pd.read_csv("part_b_input_dataset_2.csv")

# Define vehicle capacity for each dataset
vehicle_capacity_1 = 20
vehicle_capacity_2 = 30

# Function to calculate distance between two points
def calculate_distance(point1, point2):
    return ((point1['lng'] - point2['lng']) ** 2 + (point1['lat'] - point2['lat']) ** 2) ** 0.5

# Function to generate all possible routes for a given dataset and vehicle capacity
def generate_routes(input_data, vehicle_capacity):
    # Create depot node
    depot = {'order_id': 0, 'lng': input_data['depot_lng'].iloc[0], 'lat': input_data['depot_lat'].iloc[0]}

    # Create list of customer nodes
    customers = input_data[['order_id', 'lng', 'lat']].to_dict('records')

    # Generate all possible combinations of customer orders
    all_routes = []
    for order_combination in itertools.permutations(customers[1:], len(customers) - 1):
        route = [depot] + list(order_combination) + [depot]
        # Check if route satisfies vehicle capacity constraint
        if len(route) <= vehicle_capacity + 2:
            all_routes.append(route)

    return all_routes

# Function to calculate total distance travelled for a route
def calculate_total_distance(route):
    total_distance = 0
    for i in range(len(route) - 1):
        total_distance += calculate_distance(route[i], route[i + 1])
    return total_distance

# Function to find the best route combination with minimum total distance
def find_best_routes(routes, vehicle_capacity):
    min_total_distance = float('inf')
    best_routes = []
    for route_combination in itertools.combinations(routes, 2):
        combined_route = route_combination[0] + route_combination[1][1:-1]
        if len(combined_route) <= vehicle_capacity + 2:
            total_distance = calculate_total_distance(combined_route)
            if total_distance < min_total_distance:
                min_total_distance = total_distance
                best_routes = route_combination
    return best_routes

# Generate routes for dataset 1
routes_1 = generate_routes(input_data_1, vehicle_capacity_1)

# Find the best routes for dataset 1
best_routes_1 = find_best_routes(routes_1, vehicle_capacity_1)

# Generate routes for dataset 2
routes_2 = generate_routes(input_data_2, vehicle_capacity_2)

# Find the best routes for dataset 2
best_routes_2 = find_best_routes(routes_2, vehicle_capacity_2)

# Write output datasets
output_data_1 = pd.DataFrame(best_routes_1[0], columns=["order_id", "lng", "lat"])
output_data_1["vehicle_num"] = 1
output_data_1["dlvr_seq_num"] = output_data_1.index + 1

output_data_2 = pd.DataFrame(best_routes_2[0], columns=["order_id", "lng", "lat"])
output_data_2["vehicle_num"] = 1
output_data_2["dlvr_seq_num"] = output_data_2.index + 1

output_data_1.to_csv("part_b_output_dataset_1.csv", index=False)
output_data_2.to_csv("part_b_output_dataset_2.csv", index=False)

# Calculate delivery route distance travelled across vehicles for each dataset
total_distance_1 = calculate_total_distance(best_routes_1[0])
total_distance_2 = calculate_total_distance(best_routes_2[0])

# Write delivery route distance travelled to a file
routes_distance_data = {
    "Dataset": ["part_b_input_dataset_1", "part_b_input_dataset_2"],
    "Vehicle 1 Route Distance": [total_distance_1, total_distance_2],
    "Vehicle 2 Route Distance": [total_distance_1, total_distance_2],
    "Total Distance Travelled": [total_distance_1 + total_distance_2] * 2
}

routes_distance_df = pd.DataFrame(routes_distance_data)
routes_distance_df.to_csv("part_b_routes_distance_travelled.csv", index=False)